// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteSnippet(arg1:string):Promise<void>;

export function GetSnippets():Promise<{[key: string]: main.Snippet}>;

export function GetTags():Promise<{[key: string]: number}>;

export function GetUUID():Promise<string>;

export function RenderSnippet(arg1:string):Promise<string>;

export function SaveSnippet(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:string):Promise<main.Snippet>;
