// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSnippet(arg1) {
  return window['go']['main']['App']['DeleteSnippet'](arg1);
}

export function GetSnippets() {
  return window['go']['main']['App']['GetSnippets']();
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function GetUUID() {
  return window['go']['main']['App']['GetUUID']();
}

export function RenderSnippet(arg1) {
  return window['go']['main']['App']['RenderSnippet'](arg1);
}

export function SaveSnippet(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveSnippet'](arg1, arg2, arg3, arg4, arg5);
}
